/* CVLab — shared member data
   Replace with real data later. Images use randomuser.me portraits (placeholder). */

const LAB_INFO = {
  name: "CVLab",
  shortName: "CVLab",
  university: "Iran University of Science and Technology",
  department: "Department of Computer Engineering",
  email: "contact@cvlab.university.edu",
  location: "Engineering Building, Room 404",
  heroTitle: "CVLab",
  heroSubtitle:
    "We are a research laboratory focused on machine learning, computer vision, natural language processing, and trustworthy AI. Our mission is to conduct rigorous, open, and impactful research — and to train the next generation of AI researchers.",
  founded: "2019",
  researchAreas: [
    { title: "Computer Vision", desc: "Detection, segmentation, generative vision and medical imaging." },
    { title: "Natural Language Processing", desc: "LLMs, reasoning, retrieval and multilingual models." },
    { title: "Trustworthy AI", desc: "Robustness, explainability, fairness and safety." },
    { title: "Efficient Learning", desc: "Model compression, NAS, edge AI and federated learning." },
  ],
};

const MEMBERS = [
  {
    id: "mohammadreza-mohammadi",
    name: "Dr. Mohammadreza Mohammadi",
    role: "Associate Professor · Lab Director",
    category: "Professor",
    featured: true,
    image: "profile_pics/dr_mohammadi.jpeg",
    shortBio: "Leads the lab. Research focuses on computer vision, machine learning, and AI applications.",
    tags: ["Computer Vision", "Machine Learning", "AI Applications"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "m.mohammadi@iust.ac.ir",
    location: "Room 400",
    bio: "Dr. Mohammadreza Mohammadi is an Associate Professor of Computer Engineering and the director of CVLab at Iran University of Science and Technology. His research spans computer vision, machine learning, and their applications in various domains. He has published extensively in top-tier venues and actively supervises graduate students. He welcomes inquiries from prospective MSc and PhD students.",
    education: ["Ph.D. Computer Engineering", "M.Sc. Computer Engineering"],
    interests: ["Computer Vision", "Machine Learning", "Deep Learning", "Pattern Recognition"],
    publications: [
      "Mohammadi et al. — Recent publication 1, Conference 2024",
      "Mohammadi et al. — Recent publication 2, Journal 2023",
      "Mohammadi et al. — Recent publication 3, Conference 2022",
    ],
    projects: ["Lab vision & direction", "Computer Vision Applications"],
  },
  {
    id: "sara-ahmadi",
    name: "Dr. Sara Ahmadi",
    role: "Associate Professor · PI",
    category: "Faculty",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    shortBio: "Leads research on explainable deep learning and medical image analysis.",
    tags: ["Explainable AI", "Medical Imaging", "Computer Vision"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "s.ahmadi@university.edu",
    location: "Room 401",
    bio: "Dr. Sara Ahmadi leads the medical imaging research line of CVLab. Her work focuses on building interpretable and reliable vision systems for healthcare, with 60+ peer-reviewed papers in MICCAI, NeurIPS, and IEEE-TMI. She supervises PhD and MSc students and collaborates with university hospitals.",
    education: ["Ph.D. Computer Science, ETH Zurich (2016)", "M.Sc. AI, University of Tehran (2011)"],
    interests: ["Explainable AI", "Medical Image Analysis", "Vision Transformers", "Uncertainty Quantification"],
    publications: [
      "Ahmadi et al. — Interpretable Vision Transformers for Histopathology, MICCAI 2024",
      "Ahmadi et al. — Calibrated Uncertainty in Medical Segmentation, IEEE-TMI 2023",
      "Ahmadi et al. — Self-supervised Pretraining for Radiology, NeurIPS 2022",
    ],
    projects: ["TrustMed — Explainable diagnostics", "PathoVision — Whole-slide analysis"],
  },
  {
    id: "reza-karimi",
    name: "Reza Karimi",
    role: "Ph.D. Candidate",
    category: "PhD",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    shortBio: "Works on large language models, reasoning and retrieval-augmented generation.",
    tags: ["LLMs", "NLP", "RAG"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "r.karimi@university.edu",
    location: "Room 404-A",
    bio: "Reza is a 3rd-year PhD student working on reasoning in large language models and efficient retrieval-augmented generation. Previously an ML engineer, he is interested in evaluation and long-context understanding.",
    education: ["M.Sc. Computer Engineering (2022)", "B.Sc. Software Engineering (2019)"],
    interests: ["Large Language Models", "Retrieval-Augmented Generation", "Evaluation"],
    publications: [
      "Karimi et al. — Faithful RAG with Citation Grounding, ACL 2025 (under review)",
      "Karimi et al. — Long-context Benchmarking, EMNLP Workshop 2024",
    ],
    projects: ["CiteRAG — Grounded QA", "LongEval toolkit"],
  },
  {
    id: "maryam-hosseini",
    name: "Maryam Hosseini",
    role: "Ph.D. Candidate",
    category: "PhD",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    shortBio: "Focuses on diffusion models and generative vision for data-scarce domains.",
    tags: ["Diffusion Models", "Generative AI", "Computer Vision"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "m.hosseini@university.edu",
    location: "Room 404-A",
    bio: "Maryam researches generative modeling, particularly diffusion models for medical and synthetic data generation. She maintains the lab's generative-vision reading group.",
    education: ["M.Sc. AI (2021)"],
    interests: ["Diffusion Models", "Synthetic Data", "Image Editing"],
    publications: ["Hosseini et al. — Controllable Diffusion for Histology Synthesis, ICCV Workshop 2023"],
    projects: ["SynPath — Synthetic pathology data"],
  },
  {
    id: "ali-najafi",
    name: "Ali Najafi",
    role: "M.Sc. Student",
    category: "MSc",
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    shortBio: "Interested in efficient deep learning, pruning and edge deployment.",
    tags: ["Model Compression", "Edge AI", "PyTorch"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "a.najafi@university.edu",
    location: "Room 404-B",
    bio: "Ali works on pruning and quantization of vision transformers for edge devices. He contributes to the lab's open-source compression library.",
    education: ["B.Sc. Computer Engineering (2023)"],
    interests: ["Pruning", "Quantization", "Jetson / Edge Deployment"],
    publications: ["Najafi et al. — Latency-aware Pruning of ViTs (preprint 2025)"],
    projects: ["EdgeViT — Real-time inference toolkit"],
  },
  {
    id: "neda-rahimi",
    name: "Neda Rahimi",
    role: "M.Sc. Student",
    category: "MSc",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    shortBio: "Works on vision-language models and multimodal grounding.",
    tags: ["VLM", "Multimodal", "Detection"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "n.rahimi@university.edu",
    location: "Room 404-B",
    bio: "Neda explores open-vocabulary detection and vision-language alignment. She previously interned as a computer vision engineer.",
    education: ["B.Sc. Computer Science (2023)"],
    interests: ["Vision-Language Models", "Open-vocabulary Detection"],
    publications: [],
    projects: ["GroundLab — Phrase grounding demo"],
  },
  {
    id: "daniel-miller",
    name: "Daniel Miller",
    role: "Undergraduate Research Assistant",
    category: "Undergrad",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    shortBio: "Assists with datasets, benchmarks and reinforcement learning experiments.",
    tags: ["Reinforcement Learning", "Benchmarks", "Python"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "d.miller@university.edu",
    location: "Room 404-C",
    bio: "Daniel is a senior undergrad supporting RL experiments and dataset curation. He is applying for MSc positions in Fall.",
    education: ["B.Sc. in progress (2026)"],
    interests: ["Deep RL", "Robotics Simulators"],
    publications: [],
    projects: ["RLBench-Lite"],
  },
  {
    id: "lina-chen",
    name: "Lina Chen",
    role: "Postdoctoral Researcher",
    category: "Faculty",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    shortBio: "Researches federated learning, privacy and distributed optimization.",
    tags: ["Federated Learning", "Privacy", "Optimization"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "l.chen@university.edu",
    location: "Room 402",
    bio: "Lina joined as a postdoc after her PhD on privacy-preserving distributed learning. She leads the lab's collaboration on federated medical AI.",
    education: ["Ph.D. Machine Learning, TU Munich (2024)"],
    interests: ["Federated Learning", "Differential Privacy"],
    publications: [
      "Chen et al. — Communication-efficient Federated ViTs, ICLR 2024",
      "Chen et al. — Private Aggregation for Hospitals, Nature MI 2023",
    ],
    projects: ["FedMed — Cross-hospital learning"],
  },
  {
    id: "omid-tavakoli",
    name: "Omid Tavakoli",
    role: "Research Engineer",
    category: "Staff",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    shortBio: "Maintains lab infrastructure, MLOps pipelines and demo deployments.",
    tags: ["MLOps", "LLM Serving", "Docker"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "o.tavakoli@university.edu",
    location: "Lab Server Room",
    bio: "Omid keeps the lab running: GPU cluster, experiment tracking, and public demos. He loves clean pipelines and reproducible research.",
    education: ["B.Sc. IT Engineering"],
    interests: ["MLOps", "vLLM / Triton", "Experiment Tracking"],
    publications: [],
    projects: ["LabStack — Internal MLOps platform"],
  },
];
