/* CVLab — shared member data */

const LAB_INFO = {
  name: "ICVLab",
  shortName: "ICVLab",
  university: "Iran University of Science and Technology",
  department: "Department of Computer Engineering",
  email: "contact@cvlab.university.edu",
  location: "2nd Floor, Computer Engineering Building",
  heroTitle: "ICVLab",
  heroSubtitle:
    "Computer Vision Laboratory of the Department of Artificial Intelligence and Robotics, School of Computer Engineering at Iran University of Science and Technology.",
  founded: "2019",
  researchAreas: [
    { title: "Computer Vision", icon: "👁️", desc: "Detection, segmentation, generative vision, and visual understanding." },
    { title: "Deep Learning", icon: "🧠", desc: "Neural network architectures, representation learning, and optimization." },
    { title: "Multimodal", icon: "🔀", desc: "Vision-language models, cross-modal reasoning, and multimodal grounding." },
    { title: "Agentic AI", icon: "🤖", desc: "Autonomous agents, visual reasoning, tool use, and decision-making." },
  ],
};

const MEMBERS = [
  {
    id: "mohammadreza-mohammadi",
    name: "Dr. Mohammadreza Mohammadi",
    role: "Associate Professor · Lab Director",
    category: "Associated Professor",
    featured: true,
    image: "profile_pics/dr_mohammadi.jpeg",
    shortBio: "Leads the lab. Research focuses on computer vision, machine learning, and AI applications.",
    tags: ["Computer Vision", "Machine Learning", "AI Applications"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "m.mohammadi@iust.ac.ir",
    location: "Room 400",
    bio: "Dr. Mohammadreza Mohammadi is an Associate Professor of Computer Engineering and the director of ICVLab at Iran University of Science and Technology. His research spans computer vision, machine learning, and their applications in various domains. He has published extensively in top-tier venues and actively supervises graduate students.",
    education: ["Ph.D. Computer Engineering", "M.Sc. Computer Engineering"],
    interests: ["Computer Vision", "Machine Learning", "Deep Learning", "Pattern Recognition"],
    publications: [
      "Mohammadi et al. — Recent publication 1, Conference 2024",
      "Mohammadi et al. — Recent publication 2, Journal 2023",
      "Mohammadi et al. — Recent publication 3, Conference 2022",
    ],
    projects: ["Lab vision & direction", "Computer Vision Applications"],
  },
  {
    id: "amirreza-fateh",
    name: "Amirreza Fateh",
    role: "Ph.D. Student",
    category: "PhD",
    image: "profile_pics/Amirreza_Fateh.jpg",
    shortBio: "Investigating generative models, image synthesis, and visual perception.",
    tags: ["Generative AI", "Computer Vision", "Diffusion"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "amirreza_fateh@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Amirreza Fateh is a Ph.D. student and researcher at ICVLab focusing on generative models, image synthesis, and neural reconstruction.",
    education: ["Ph.D. Student in Computer Engineering, IUST"],
    interests: ["Generative Models", "Diffusion Models", "Computer Vision"],
    publications: [],
    projects: ["Generative Vision Frameworks"],
  },
  {
    id: "alireza-sedighimoghadam",
    name: "Alireza Sedighi Moghadam",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Alireza_SedighiMoghadam.jpeg",
    shortBio: "Focuses on deep learning architectures, computer vision, and representation learning.",
    tags: ["Computer Vision", "Deep Learning", "PyTorch"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "sedighimoghadam@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Alireza Sedighi Moghadam is a researcher at ICVLab focusing on advanced computer vision architectures and neural representations.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Computer Vision", "Representation Learning", "Deep Learning"],
    publications: [],
    projects: ["Visual Representation Learning"],
  },
  {
    id: "amin-chiniforushan",
    name: "Amin Chiniforushan",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Amin_Chiniforushan.jpg",
    shortBio: "Researching multimodal learning, vision transformers, and image understanding.",
    tags: ["Vision Transformers", "Multimodal", "Vision"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "chiniforushan@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Amin Chiniforushan conducts research on vision transformers, multimodal learning, and visual reasoning systems.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Vision Transformers", "Multimodal AI", "Image Recognition"],
    publications: [],
    projects: ["Vision Transformer Architectures"],
  },
  {
    id: "arash-farzaneh",
    name: "Arash Farzaneh",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Arash_Farzaneh.jpg",
    shortBio: "Working on computer vision, deep neural networks, and scalable AI models.",
    tags: ["Computer Vision", "Machine Learning", "Deep Learning"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "arash_farzaneh@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Arash Farzaneh is a researcher at ICVLab at Iran University of Science and Technology, specializing in deep learning, visual perception, and machine learning pipelines.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Computer Vision", "Deep Learning", "Pattern Analysis", "Neural Networks"],
    publications: [],
    projects: ["Scalable Vision Models", "ICVLab Platform"],
  },
  {
    id: "sadegh-poulaei",
    name: "Sadegh Poulaei",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Sadegh_Poulaei.jpg",
    shortBio: "Focusing on computer vision, deep neural networks, and pattern intelligence.",
    tags: ["Computer Vision", "Deep Learning", "Pattern Recognition"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "sadegh_poulaei@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Sadegh Poulaei is a graduate researcher at ICVLab at Iran University of Science and Technology, specializing in computer vision and deep learning architectures.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Computer Vision", "Deep Learning", "Neural Networks"],
    publications: [],
    projects: ["Visual Learning Models"],
  },
  {
    id: "mehrshad-fallah",
    name: "Mehrshad Fallah",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Mehrshad_Fallah.jpg",
    shortBio: "Researching computer vision, deep learning representations, and intelligent systems.",
    tags: ["Computer Vision", "Deep Learning", "Pattern Recognition"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "mehrshad_fallah@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Mehrshad Fallah is a graduate researcher at ICVLab at Iran University of Science and Technology, focusing on computer vision and deep learning models.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Computer Vision", "Deep Learning", "Visual Representation"],
    publications: [],
    projects: ["Deep Vision Systems"],
  },
  {
    id: "kamyar-moradian",
    name: "Kamyar Moradian",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Kamyar_Moradian.jpeg",
    shortBio: "Investigating deep learning, semantic segmentation, and automated vision.",
    tags: ["Segmentation", "Deep Learning", "Vision"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "kamyar_moradian@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Kamyar Moradian is a researcher at ICVLab with a focus on visual segmentation, deep learning, and robust computer vision systems.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Semantic Segmentation", "Deep Learning", "Image Analysis"],
    publications: [],
    projects: ["Semantic Segmentation Toolkit"],
  },
  {
    id: "mahdi-khoursha",
    name: "Mahdi Khoursha",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Mahdi_Khoursha.jpeg",
    shortBio: "Focuses on efficient neural networks, model optimization, and edge inference.",
    tags: ["Model Optimization", "Edge AI", "Deep Learning"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "mahdi_khoursha@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Mahdi Khoursha is a researcher exploring efficient neural network design, model compression, and high-performance inference.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Model Optimization", "Efficient Learning", "Computer Vision"],
    publications: [],
    projects: ["Efficient Deep Learning Inference"],
  },
  {
    id: "mohammadreza-tajik",
    name: "Mohammadreza Tajik",
    role: "Graduate Researcher",
    category: "MSc",
    image: "profile_pics/Mohammadreza_Tajik.jpeg",
    shortBio: "Working on visual feature learning, pattern recognition, and self-supervised AI.",
    tags: ["Pattern Recognition", "Feature Learning", "Vision"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "mohammadreza_tajik@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Mohammadreza Tajik investigates self-supervised learning, pattern recognition, and feature extraction for computer vision tasks.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Self-Supervised Learning", "Pattern Recognition", "Feature Representation"],
    publications: [],
    projects: ["Self-Supervised Vision"],
  },
  {
    id: "attila-roshani",
    name: "Attila Roshani",
    role: "Graduate Researcher",
    category: "BSc",
    image: "profile_pics/Attila_Roshani.jpeg",
    shortBio: "Working on real-time visual tracking, detection, and scene perception.",
    tags: ["Object Detection", "Tracking", "Real-time AI"],
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    email: "attila_roshani@iust.ac.ir",
    location: "Lab Room 404",
    bio: "Attila Roshani researches real-time object tracking, detection systems, and dynamic scene understanding at ICVLab.",
    education: ["M.Sc. Student in Computer Engineering, IUST"],
    interests: ["Object Tracking", "Object Detection", "Edge Vision"],
    publications: [],
    projects: ["Dynamic Scene Perception"],
  },
];
